services:
  - type: web
    name: placement-tracker-api
    env: node
    plan: starter
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
