export const OFFICIAL_2026 = {
  title: 'Batch Graduating in 2026',
  companies: 199,
  full_time_companies: 162,
  summer_internship_companies: 37,
  total_offers: 841,
  full_time_offers: 659,
  internship_offers: 182,
  categories: [
    { label: 'A+ offers', value: 354, note: 'CTC >= 12.50 LPA' },
    { label: 'A offers', value: 220, note: '7 LPA < CTC < 12.00 LPA' },
    { label: 'B offers', value: 85, note: 'CTC below 7 LPA' },
  ],
  indian_offers: 656,
  overseas_offers: 3,
  highest_indian_btech_lpa: 72.30,
  highest_indian_mtech_lpa: 30.86,
  highest_overseas_lpa: 48.65,
  average_btech_lpa: 19.87,
  average_mtech_lpa: 16.31,
  overall_average_lpa: 18.77,
  campus_placement_percentage: 89.64,
  note: 'An additional B category option was implemented to create more job opportunities for students.',
  programs: {
    'B.Tech': [
      { label: 'CSE', value: 97.41 },
      { label: 'ECE', value: 69.70 },
      { label: 'CSAM', value: 92.73 },
      { label: 'CSD', value: 97.78 },
      { label: 'CSSS', value: 90.24 },
      { label: 'CSB', value: 90.91 },
      { label: 'CSAI', value: 92.00 },
      { label: 'EVE', value: 87.50 },
    ],
    'M.Tech': [
      { label: 'CSE', value: 95.16 },
      { label: 'ECE', value: 71.43 },
      { label: 'CB', value: 63.64 },
    ],
  },
};
