export const OFFICIAL_2025 = {
  title: 'Batch Graduated in 2025',
  companies: 207,
  full_time_companies: 167,
  summer_internship_companies: 40,
  total_offers: 769,
  full_time_offers: 559,
  internship_offers: 210,
  categories: [
    { label: 'A+ offers', value: 353, note: 'CTC >= 12.50 LPA' },
    { label: 'A offers', value: 183, note: '7 LPA < CTC < 12 LPA' },
    { label: 'B offers', value: 23, note: 'CTC below 7 LPA' },
  ],
  indian_offers: 550,
  overseas_offers: 9,
  highest_indian_btech_lpa: 51.31,
  highest_indian_mtech_lpa: 38.84,
  highest_overseas_lpa: 107,
  average_btech_lpa: 21,
  average_mtech_lpa: 17.26,
  overall_average_lpa: 19.79,
  campus_placement_percentage: 88.30,
  programs: {
    'B.Tech': [
      { label: 'CSE', value: 93.55 },
      { label: 'ECE', value: 96.43 },
      { label: 'CSAM', value: 98.28 },
      { label: 'CSD', value: 82.93 },
      { label: 'CSSS', value: 87.88 },
      { label: 'CSB', value: 90.48 },
      { label: 'CSAI', value: 95.92 },
    ],
    'M.Tech': [
      { label: 'CSE', value: 86.32 },
      { label: 'ECE', value: 81.82 },
      { label: 'CB', value: 46.15 },
    ],
  },
};
